export class AdminOrder {
    constructor(
        public userId: number,
        public userName: string,
        public userEmail: string,
        public firstName: string,
        public lastName: string,
        public streetAddress: string,
        public postalCode: number,
        public city: string,
        public state: string,
        public country: string,
        public phoneNumber: number,
        public addressEmail: string,
        public orderId: number,
        public productImage: string,
        public productName: string,
        public price: number,
        public quantity: number,
        public subTotal: number,
        public total: number,
        public receipt: string,
        public orderDetails: string,
        public razorPayOrderId: string,
        public modeOfPayment: string,
        public orderStatusId: number,
        public orderStatusDetails: string,
        public updateByAdminId: string,
        public created_at: Date,
        public updated_at: Date
    ) { }
}
